version: "3.8"

services: 
  nginx:
    build: 
      context: req/nginx/.
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wp
      - mdb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception-network
    restart: always

  wp:
    build:
      context: req/wp/.
      dockerfile: Dockerfile
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      mdb:
        condition: service_healthy
    volumes:
      - ./web:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - inception-network
    restart: always

  mdb:
    build: 
      context: req/mdb/.
      dockerfile: Dockerfile
    container_name: mdb
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5

networks:
  inception-network:
    driver: bridge

