services:
  nginx:
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - inception-network
    restart: on-failure
    secrets:
      - db_name
      - db_user
      - db_root_pass
      - wp_admin
      - wp_admin_pass
      - wp_usr
      - wp_usr_pass

  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    environment:
      WP_URL: "localhost"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 5
    secrets:
      - db_name
      - db_user
      - db_root_pass
  
  redis:
    build: 
      context: ./requirements/bonus/redis/.
      dockerfile: Dockerfile
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - inception-network
    restart: on-failure
    volumes:
          - wordpress:/var/www/html

  ftp:
    build:
      context: ./requirements/bonus/ftp/.
      dockerfile: Dockerfile
    container_name: ftp
    image: ftp
    ports:
      - "20-21:20-21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network
    environment:
      FTP_USER: "admin"
      FTP_PASS: "admin"
      PASV_ADDRESS: "localhost"
      PASV_MIN_PORT: "21000"
      PASV_MAX_PORT: "21010"

  website:
    build:
      context: ./requirements/bonus/website/.
      dockerfile: Dockerfile
    container_name: website
    image: website
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-network

  adminer:
    image: adminer:4.8.0
    ports:
      - "8085:8080"
    depends_on:
      - mariadb
    container_name: adminer
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress1
      o: bind
  
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb1
      o: bind

secrets:
  db_name:
    file: ./secrets/db_name.txt
  db_user:
    file: ./secrets/db_user.txt
  db_root_pass:
    file: ./secrets/db_root_pass.txt
  
  wp_admin:
    file: ./secrets/wp_admin.txt
  wp_admin_pass:
    file: ./secrets/wp_admin_pass.txt
  
  wp_usr:
    file: ./secrets/wp_usr.txt
  wp_usr_pass:
    file: ./secrets/wp_usr_pass.txt